service: service-hello

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  sayHello:
    handler: dist/lambdas/hello.handler
    name: sayHello
    timeout: 5
    memorySize: 256
    events:
      - http:
          path: /hello
          method: get
