service: backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${env:ENVIRONMENT}
  region: us-east-1
  environment:
    JWT_SECRET: ${ssm:auth-jwt-secret}
    DATABASE_URL: ${ssm:mysql-db-url}

plugins:
  - serverless-webpack
  - serverless-webpack-prisma

custom:
  webpack:
    includeModules: true

functions:
  authorize:
    handler: dist/src/auth/authorize/handler.handler
    name: ${self:provider.stage}-${self:service}-authorize
    tags:
      name: authorize
    timeout: 10
    memorySize: 128

  createAccount:
    handler: dist/src/accounts/create-account/handler.handler
    name: ${self:provider.stage}-${self:service}-createAccount
    tags:
      name: createAccount
    timeout: 15
    memorySize: 128
    events:
      - http:
          path: /accounts
          method: post

  getUsers:
    handler: dist/src/users/get-users/handler.handler
    name: ${self:provider.stage}-${self:service}-getUsers
    tags:
      name: getUsers
    timeout: 10
    memorySize: 128
    events:
      - http:
          path: /users
          method: get
          authorizer:
            name: authorize
            identitySource: method.request.header.Authorization
            type: token
