version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "yarn.lock" }}
            - dependencies-cache

      - run:
          name: Install Serverless CLI
          command: npm i -g serverless

      - run:
          name: Install dependencies
          command: |
            sudo yarn install

      - run:
          name: Deploy application
          command: |
            sls deploy

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "yarn.lock" }}

workflows:
  build-deploy:
    jobs:
      - deploy
