version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Serverless CLI
          command: sudo npm install serverless -g
      - run:
          name: Install dependencies
          command: sudo npm install
      - run:
          name: Run type check
          command: sudo npm run test-check
      - run:
          name: Run lint check
          command: sudo npm run lint
      - run:
          name: Test src
          command: sudo npm run test:src
      - run:
          name: Test libs
          command: sudo npm run test:libs
  deploy:
    docker:
      - image: circleci/node:14
    environment:
      ENVIRONMENT: staging
    steps:
      - checkout
      - run:
          name: Deploy application
          command: sls deploy

workflows:
  test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
