version: 2.1

jobs:
  build_deploy_staging_job:
    docker:
      - image: circleci/node:14
    environment:
      ENVIRONMENT: staging

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package-lock.json" }}
            - dependencies-cache

      - run:
          name: Install Serverless CLI
          command: sudo npm install serverless -g

      - run:
          name: Install dependencies
          command: sudo npm install

      - run:
          name: Build dependencies
          command: npm run build

      - run:
          name: Deploy application
          command: sls deploy

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package-lock.json" }}

workflows:
  build_deploy_staging_workflow:
    jobs:
      - build_deploy_staging_job:
          filters:
            branches:
              only:
                - develop
