version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo npm install
      - run:
          name: Run type check
          command: npm run type-check
      - run:
          name: Run lint check
          command: npm run lint
#      - run:
#          name: Test src
#          command: npm run test:src
      - run:
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    docker:
      - image: circleci/node:14
    environment:
      ENVIRONMENT: staging
    steps:
      - run:
          name: Install Serverless CLI
          command: sudo npm install serverless -g
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy application
          command: sls deploy

workflows:
  test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
